name: test_my_project
on:
  push:
  pull_request:
jobs:
  test-job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Starting message 
      run: echo "Starting tests"
    - name: Git clone my repo
      uses: actions/checkout@v1
