name: Test_my_functions

on:
  push:
    branches: [ main ]
  pull_request:   
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install_python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Run_test
        run: test
