name: Test_me

on: [push, workflow_dispatch]

jobs:
  try_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: start test_max
        id: test_max
        continue-on-error: true
        run: python -m unittest test_max.py
        
      - name: start test_min
        id: test_min
        continue-on-error: true
        run: python -m unittest test_min.py
        
      - name: start test_sum
        id: test_sum
        continue-on-error: true
        run: python -m unittest test_sum.py
        
      - name: start test_prod
        id: test_prod
        continue-on-error: true
        run: python -m unittest test_prod.py
        
      - name: start test_mean
        id: test_mean
        continue-on-error: true
        run: python -m unittest test_mean.py
        
      - name: start test_time
        id: test_time
        continue-on-error: true
        run: python -m unittest test_time.py
      
      - name: telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            ${{ github.actor }} внёс изменения в репозиторий:
            Изменения: ${{ github.event.commits[0].message }}
            
            Результаты тестов:
            1) Тест на корректное считывание: <b><u>${{ steps.test_max }}</u></b>
            2) Тест на корректное вычисление минимума: <b><u>${{ steps.test_min }}</u></b>
            3) Тест на корректное вычисление максимума: <b><u>${{ steps.test_sum }}</u></b>
            4) Тест на корректное вычисление суммы: <b><u>${{ steps.test_prod }}</u></b>
            5) Тест на корректное вычисление произведения: <b><u>${{ steps.test_time }}</u></b>
            6) Тесты на скорость: <b><u>${{ steps.test_mean }}</u></b>
